services:
  # Monitoring & logging backend
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    environment:
      - ZO_ROOT_USER_EMAIL=admin@example.com
      - ZO_ROOT_USER_PASSWORD=password123
    ports:
      - "3205:5080" # Web UI
    volumes:
      - o2_data:/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./infra/otel-config.yaml:/etc/otel/config.yaml
      - ./backend/logs:/etc/app/logs:ro
    command: ["--config=/etc/otel/config.yaml"]
    ports:
      - "3217:4317" # OTLP gRPC
      - "3218:4318" # OTLP HTTP
    depends_on:
      - openobserve

  redis:
    image: redis:7-alpine
    container_name: tidsapparat_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # Saves every 60 seconds if at least 1 key changes
    command: redis-server --save 60 1 --loglevel warning

  redisinsight:
    image: redis/redisinsight:latest
    container_name: tidsapparat_redisinsight
    environment:
      - RI_APP_PORT=5540
      - RI_APP_HOST=0.0.0.0
      - RI_ACCEPT_TERMS_AND_CONDITIONS=true
      - RI_REDIS_ALIAS0=Tidsapparat-Redis
      - RI_REDIS_HOST0=tidsapparat_redis
      - RI_REDIS_PORT0=6379
    ports:
      - "3206:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis

  minio:
    image: minio/minio:latest
    container_name: demoparty_minio
    ports:
      - "9000:9000"
      - "3207:9001"
    environment:
      - MINIO_ROOT_USER=local-admin
      - MINIO_ROOT_PASSWORD=local-super-secret
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    container_name: demoparty_minio_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local_minio http://minio:9000 local-admin local-super-secret) do echo 'Waiting for MinIO...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing local_minio/demoparty-exports;
      /usr/bin/mc anonymous set download local_minio/demoparty-exports;
      exit 0;
      "

volumes:
  o2_data:
  redis_data:
  redisinsight_data:
  minio_data:
